### ISSUE TITLE
What do this firmware?

### ISSUE THREAD

**Issue by onlineapps-cloud** [ultimateshadsform/Anycubic-Kobra-2-Series-Firmware#5]
Hi, i have anycubic kobra 2 max, i want to install your firmware, but from description is not clear what do your firmware? what's different betwen original firmware? i can use it with octoprint on example? can you add some detailed info about what do this firmware? thanks for your work. best regards.

**Comment by ultimateshadsform** [comment]
This is just the original stock firmware.

Nothing special about it.

There isn't any custom firmware at the moment.
