### ISSUE TITLE
Cant download the firmware anymore :(

### ISSUE THREAD

**Issue by EinfachRobbe** [ultimateshadsform/Anycubic-Kobra-2-Series-Firmware#7]
When I try to download the firmware with lfs I get the bandwidth error and when I'm trying to download directly with curl I only download the lfs file as zip. I can't find another firmware download, please help.

**Comment by ultimateshadsform** [comment]
Can you try now see if it works?

**Comment by EinfachRobbe** [comment]
I will be home later, then I will try it.

**Comment by ultimateshadsform** [comment]
Did it work?

**Comment by EinfachRobbe** [comment]
> Did it work?

Yes! You're the best!
